services:
  wireguard:
    #image: linuxserver/wireguard
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - SERVERURL=liberalismen.dk
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
        #- PEERDNS=auto #optional
      - PEERDNS=8.8.8.8  # DNS for peers, default is Google DNS
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config:/config   # Stores the configuration files
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    restart: unless-stopped

